In [4]:
import pandas as pd
dataset=pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend      State     Profit
0    78013.11       121597.55        264346.06  Tamilnadu  126992.93
1    86419.70       153514.11        293917.57  Bangalore  122776.86
2    91992.39       135495.07        252664.93     Kerala  134307.35
3    93863.75       127320.38        249839.44  Tamilnadu  141585.52
4    94657.16       145077.58        282574.31     Kerala  125370.37
5   100671.96        91790.61        249744.55  Bangalore  144259.40
6   114523.61       122616.84        261776.23  Bangalore  129917.04
7   120542.52       148718.95        311613.29  Tamilnadu  152211.77
8   123334.88       108679.17        304981.62     Kerala  149759.96
9   130298.13       145530.06        323876.68  Bangalore  155752.60
10  131876.90        99814.71        362861.36     Kerala  156991.12
11  142107.34        91391.77        366168.42  Tamilnadu  166187.94
12  144372.41       118671.85        383199.62  Bangalore  182901.10
13  162597.70       151377.59        443898.53     Kerala  191792.06
14  165349.20       136897.80        471784.10  Tamilnadu  192261.83
15   78013.11       121597.55        264346.06  Tamilnadu  126992.93
16   86419.70       153514.11        293917.57  Bangalore  122776.86
17   91992.39       135495.07        252664.93     Kerala  134307.35
18   93863.75       127320.38        249839.44  Tamilnadu  141585.52
19   94657.16       145077.58        282574.31     Kerala  125370.37
20  100671.96        91790.61        249744.55  Bangalore  144259.40
21  114523.61       122616.84        261776.23  Bangalore  129917.04
22  120542.52       148718.95        311613.29  Tamilnadu  152211.77
23  123334.88       108679.17        304981.62     Kerala  149759.96
24  130298.13       145530.06        323876.68  Bangalore  155752.60
25  131876.90        99814.71        362861.36     Kerala  156991.12
26  142107.34        91391.77        366168.42  Tamilnadu  166187.94
27  144372.41       118671.85        383199.62  Bangalore  182901.10
28  162597.70       151377.59        443898.53     Kerala  191792.06
29  165349.20       136897.80        471784.10  Tamilnadu  192261.83
30   78013.11       121597.55        264346.06  Tamilnadu  126992.93
31   86419.70       153514.11        293917.57  Bangalore  122776.86
32   91992.39       135495.07        252664.93     Kerala  134307.35
33   93863.75       127320.38        249839.44  Tamilnadu  141585.52
34   94657.16       145077.58        282574.31     Kerala  125370.37

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Kerala,State_Tamilnadu
0,78013,121597,264346,126992,0,1
1,86419,153514,293917,122776,0,0
2,91992,135495,252664,134307,1,0
3,93863,127320,249839,141585,0,1
4,94657,145077,282574,125370,1,0
5,100671,91790,249744,144259,0,0
6,114523,122616,261776,129917,0,0
7,120542,148718,311613,152211,0,1
8,123334,108679,304981,149759,1,0
9,130298,145530,323876,155752,0,0
10,131876,99814,362861,156991,1,0
11,142107,91391,366168,166187,0,1
12,144372,118671,383199,182901,0,0
13,162597,151377,443898,191792,1,0
14,165349,136897,471784,192261,0,1
15,78013,121597,264346,126992,0,1
16,86419,153514,293917,122776,0,0
17,91992,135495,252664,134307,1,0
18,93863,127320,249839,141585,0,1
19,94657,145077,282574,125370,1,0
20,100671,91790,249744,144259,0,0
21,114523,122616,261776,129917,0,0
22,120542,148718,311613,152211,0,1
23,123334,108679,304981,149759,1,0
24,130298,145530,323876,155752,0,0
25,131876,99814,362861,156991,1,0
26,142107,91391,366168,166187,0,1
27,144372,118671,383199,182901,0,0
28,162597,151377,443898,191792,1,0
29,165349,136897,471784,192261,0,1
30,78013,121597,264346,126992,0,1
31,86419,153514,293917,122776,0,0
32,91992,135495,252664,134307,1,0
33,93863,127320,249839,141585,0,1
34,94657,145077,282574,125370,1,0

In [6]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Kerala', 'State_Tamilnadu'],
      dtype='object')

In [11]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State_Kerala', 'State_Tamilnadu']]
independent

    R&D Spend  Administration  Marketing Spend  State_Kerala  State_Tamilnadu
0       78013          121597           264346             0                1
1       86419          153514           293917             0                0
2       91992          135495           252664             1                0
3       93863          127320           249839             0                1
4       94657          145077           282574             1                0
5      100671           91790           249744             0                0
6      114523          122616           261776             0                0
7      120542          148718           311613             0                1
8      123334          108679           304981             1                0
9      130298          145530           323876             0                0
10     131876           99814           362861             1                0
11     142107           91391           366168             0                1
12     144372          118671           383199             0                0
13     162597          151377           443898             1                0
14     165349          136897           471784             0                1
15      78013          121597           264346             0                1
16      86419          153514           293917             0                0
17      91992          135495           252664             1                0
18      93863          127320           249839             0                1
19      94657          145077           282574             1                0
20     100671           91790           249744             0                0
21     114523          122616           261776             0                0
22     120542          148718           311613             0                1
23     123334          108679           304981             1                0
24     130298          145530           323876             0                0
25     131876           99814           362861             1                0
26     142107           91391           366168             0                1
27     144372          118671           383199             0                0
28     162597          151377           443898             1                0
29     165349          136897           471784             0                1
30      78013          121597           264346             0                1
31      86419          153514           293917             0                0
32      91992          135495           252664             1                0
33      93863          127320           249839             0                1
34      94657          145077           282574             1                0

In [12]:
dependent=dataset[['Profit']]
dependent

    Profit
0   126992
1   122776
2   134307
3   141585
4   125370
5   144259
6   129917
7   152211
8   149759
9   155752
10  156991
11  166187
12  182901
13  191792
14  192261
15  126992
16  122776
17  134307
18  141585
19  125370
20  144259
21  129917
22  152211
23  149759
24  155752
25  156991
26  166187
27  182901
28  191792
29  192261
30  126992
31  122776
32  134307
33  141585
34  125370

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.15,random_state=0)

In [45]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(warm_start=False, random_state=0)
regressor.fit(x_train, y_train)

C:\Users\KRISHNABALAN\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(random_state=0)

In [46]:
y_pred=regressor.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.9950541167289549

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.20,random_state=0)

In [51]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(warm_start=False, random_state=0)
regressor.fit(x_train, y_train)

C:\Users\KRISHNABALAN\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(random_state=0)

In [52]:
y_pred=regressor.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.9927296667710198

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.20,random_state=0)

In [54]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(warm_start=True, random_state=0)
regressor.fit(x_train, y_train)

C:\Users\KRISHNABALAN\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(random_state=0, warm_start=True)

In [55]:
y_pred=regressor.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.9927296667710198